name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    - name: Build
      run: docker build . -t app
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    - name: Run PHP unit tests
      run:  docker run app vendor/bin/phpunit ./tests
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    - name: Run PHP unit tests
      run: docker run -it app php ./getIp.php